### ISSUE TITLE
"decryption failure" error when trying to deploy a local charm to production JIMM

### ISSUE THREAD

**Issue by cmars** [canonical/jimm#259]
Noticed this yesterday, but I thought it was a fluke and ignored it. However, today I tried deploying myself a personal VPN into Azure, and this happened: https://pastebin.canonical.com/173748/

Retrying seems to eventually go through.

The charm is a local build of github.com/mattyw/openvpn-charm.

Juju client is 2.0.2-xenial-amd64.

The JIMM says:
```
c@zeugmatic:~$ juju show-controller jimm
jimm:
  details:
    uuid: a030379a-940f-4760-8fcf-3062b41a04e7
    api-endpoints: ['jimm.jujucharms.com:443', '162.213.33.250:443', '162.213.33.28:443']
    ca-cert: ""
    cloud: ""
    agent-version: (not implemented)
  models:
    azure-test:
      uuid: 0436e53f-68b9-4db3-8500-bc429c0447d1
      machine-count: 3
      core-count: 3
    jujugui-org:
      uuid: 509f6e4c-4da4-49c8-8f18-537c33b4d3a0
      machine-count: 48
      core-count: 48
    tempvpn:
      uuid: 8595b2b9-52e7-4440-8d88-5645b964d7a9
      machine-count: 1
      core-count: 1
  current-model: cmars@external/tempvpn
  account:
    user: cmars@external
    access: (not implemented)
```

Any other information that might be helpful, let me know!
