### ISSUE TITLE
`juju trust` from 2.4.1 does not work in JAAS

### ISSUE THREAD

**Issue by hatched** [canonical/jimm#387]
```
ubuntu@dev~ $ juju version
2.4.1-xenial-amd64
```

In JAAS
```
ubuntu@dev~ $ juju trust aws-integrator
ERROR unknown option "trust"
```

Self bootstrapped
```
ubuntu@dev~ $ juju trust wordpress
ubuntu@dev~ $ juju config wordpress
application: wordpress
application-config:
  trust:
    default: false
    description: Does this application have access to trusted credentials
    source: user
    type: bool
    value: true
```
