### ISSUE TITLE
juju show-controller output could be better

### ISSUE THREAD

**Issue by mhilton** [canonical/jimm#556]
The output of a `juju show-controller` for JAAS looks like:

```
jaas:
  details:
    uuid: a030379a-940f-4760-8fcf-3062b41a04e7
    controller-uuid: a030379a-940f-4760-8fcf-3062b41a04e7
    api-endpoints: ['jimm.jujucharms.com:443']
    cloud: ""
    agent-version: 0.0.0
    agent-git-commit: 0cc603893ea6df40b3929b9bb53695ca961328b8
    controller-model-version: (unauthorized access)
    identity-url: https://api.jujucharms.com/identity
    ca-cert: ""
  account:
    user: martin-hilton@external
    access: (not implemented)
```

We should investigate if we can make some of the values more complete. `account.access` should be possible at least.
